export const FETCH_DATA = "FETCH_DATA"
export const FETCH_DATA_FAIL = "FETCH_DATA_FAIL"
export const CURRENT_ITEM = "CURRENT_ITEM"

export const EDIT_DATA = "EDIT_DATA"


export const SET_TAGS_FILTER = "SET_TAGS_FILTER"
export const SORT_BY_COMMENTS = "SORT_BY_COMMENTS"
export const SORT_BY_LIKES = "SORT_BY_LIKES"